### ISSUE TITLE
PII in telemetry "stack" when removed from "error"

### ISSUE THREAD

**Issue by wes-carlson** [microsoft/FluidFramework#3755] opened 2020-09-25 21:34 UTC
## Describe the bug
Some errors are reported in telemetry as "Error message was removed as it contained PII", but the PII is still present in telemetry in the stack.

### Expected behavior
PII removed from errors should be removed from stack as well.

### Logs
```
Office_Fluid_FluidRuntime_Error
| where Data_error contains "Error message was removed as it contained PII"
| where Data_stack matches regex "@\\w+\\/\\w+"
| count
```
```
Count
--
6987
```

**Comment by vladsud** [comment] 2020-10-01 17:40
@wes-carloson, any chance you can help me with this item?
Here are couple things I see:
1. I've added containsPII property as quick way to solve this, but there is no synchronization between telemetry code and data store code - telemetry should expose some constant with this name and data store should use it, such that it's easy to track code and make sure it stays in sync This is assuming we do not do # 3 below.
2. We used to sanitize package names (sanitizePkgName), because ARIA would remove any event that had payload with @ sign, as it removes all data with emails. There is no reference to this API anymore, which is weird (mostly because this means '@' sign is likely goes through, which seems like wrong - we might need to follow up with telemetry folks to better understand landscape).
3. I think overall logic needs to be changed. I think relying on containsPII (i.e. consumer telling us where PII) is wrong. Instead telemetry code needs to find package names (using '@' sign) and just remove them from all fields.

**Comment by markfields** [comment] 2020-10-19 22:13
Ok I've looked into this scenario a bit while investigating #1920. I'm working with @chensixx on that fix, which will land in the November 2020 milestone. I have a solution in mind that will address # 1 for generally handling PII better, so for that aspect of this, I'd dupe this.

For # 2, I'll reach out to Jade.

For # 3, I'm skeptical that we want custom scrubbing logic... I'd rather we just build up discipline around not logging that stuff out to telemetry to begin with (i.e. I favor # 1 here).

@tylerbutler - I'd like to resolve this as dupe of #1920 but that essentially punts this until next month.  Is that ok?

cc @wes-carlson and @vladsud

**Comment by markfields** [comment] 2020-10-21 21:47
After talking with @curtisman - duping to #1920.

However, as we move closer to 3P data stores / containers being in play, we will need to keep a close eye on this, and address an even trickier case of scrubbing stack frames from 3P code we've loaded.  I'll be sure to open an issue on that to track with the appropriate 3P initiative.

**Closed by markfields** 2020-10-21 21:47 UTC
Labels: bug, telemetry
