### ISSUE TITLE
Epic: Remove _existing state from Fluid Framework (container, data store, DDS)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3429] opened 2020-08-30 18:13 UTC
At container, data store & DDS levels we have notion if "existing" which tells those layers if layer was loaded from storage (exists in a file/document) or was created locally.

There are multiple design problems with it:
1) First, the notion of "existing" is short-lived, vs. property being available all the time. This is means that it's very likely to be either incorrect or used incorrectly through lifetime of the layer
2) Code uses it to infer other type of information. this inference becomes incorrect over time as we design and build new workflows. The too latest examples are detached container, and serialization & de-serialization of detached container. In later case, we have to mimic as if layers are not existing (as they are locally created, with no delay loading required), yet other parts of the code using existing flags needs to be changed to load state from local snapshot.

Much better direction is to align all the code that uses existing with one of the following
1) In places where we pivot on creation, move / split code into creation and loading paths. These paths are becoming explicit paths across all layers
2) In places where existing flag is used to infer some other knowledge, use more appropriate and more explicit signals (might need to add them), like detached vs. not detached (container, data store, dds).

I'd suggest to use this issue as a root, and create child issues for each individual layers.
Given that most of the latest work happens at container level, I'd start there, and move downstream.

- [ ] https://github.com/microsoft/FluidFramework/issues/7223

**Comment by vladsud** [comment] 2021-05-28 01:23
Relates item - #6033
@andre4i , assigning to you. This item needs to be broken into individual work items (i.e. instantiateRuntime(), creation of Data store, creation of DDS).

**Comment by vladsud** [comment] 2022-04-07 00:45
@andre4i, that's an old issue, and I'm not sure what's left here.
Is there anything that @kian-thompson can help with? Like scoped task that is clearly defined that he can learn from and complete?

**Comment by agarwal-navin** [comment] 2022-04-07 00:55
@tyler-cai-microsoft recently created this issue - https://github.com/microsoft/FluidFramework/issues/9646 which is kinda related.

**Comment by andre4i** [comment] 2022-05-23 17:37
Duplicate of [363](https://dev.azure.com/fluidframework/internal/_workitems/edit/363)

**Closed by andre4i** 2022-05-23 17:37 UTC
Labels: refactor, api, area: runtime, epic, kr
