### ISSUE TITLE
Lost Channel Entry between Summaries

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5353] opened 2021-03-03 17:48 UTC
might be related to #5224 

We are seeing a channel go missing between summarieshttps://portal.microsofticm.com/imp/v3/incidents/details/229113984/home

**Comment by sumedhb1995** [comment] 2021-03-15 16:39
Linked IcM has been resolved via hotfix. Should this issue still be kept open @anthony-murphy ?

**Comment by ChumpChief** [comment] 2021-03-24 15:54
Removing OCE tag per note this was resolved by hotfix.

**Comment by tylerbutler** [comment] 2021-04-01 15:09
@jatgarg Can you verify that this is resolved and then close this bug? Thanks!

**Comment by jatgarg** [comment] 2021-04-05 18:41
We are not seeing this issue anymore after disabling blob deduping which we suspected could be the cause. Now we have another issue open for tracking blob deduping with this issue: https://github.com/microsoft/FluidFramework/issues/5444.
So closing this issue.

**Closed by jatgarg** 2021-04-05 18:41 UTC
Labels: bug, triage
