### ISSUE TITLE
Compare op timestamps to get lower bound for time since last summary

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#3881] opened 2020-10-08 22:37 UTC
### Problem
When opening a doc that will never receive an ack/nack from server for its latest summarize op, it will not summarize until a write client keeps the connection open for `summaryAckWaitTimeout` (currently 10 minutes). This is because it does not want to compare the server-stamped time on the "summarize" op to the client time.

### Suggestion
We can determine a lower-bound for the time since the last "summarize" op by comparing the timestamp on the "summarize" op with the timestamp of the latest received op. In majority of cases, this should occur before a client waits 10 minutes consecutively. Since it is a server-side operation we are waiting on, this should be completely acceptable behavior. Further, since the timestamps being compared are both coming from the server, comparing should be valid.

**Comment by arinwt** [comment] 2020-10-08 22:45
This is a resiliency/mitigation feature, which I think should be prioritized. In cases where something goes wrong, it will reduce the scope of the problem. Without it, there can be lingering concern and subsequent problems after the initial issue, because docs are still not summarizing for some time.

**Comment by markfields** [comment] 2020-10-29 17:25
Let's consider getting a good telemetry query to detect when this is happening to understand how common it is and maybe move towards root causes on the server

**Comment by jatgarg** [comment] 2021-02-17 23:59
Closing with https://github.com/microsoft/FluidFramework/pull/5117.

**Closed by jatgarg** 2021-02-17 23:59 UTC
Labels: area: runtime, perf
