### ISSUE TITLE
Implement Roll back hash / CRC

### ISSUE THREAD

**Issue by raandra** [microsoft/FluidFramework#5720] opened 2021-04-05 20:10 UTC
## Feature
**Is your feature request related to a problem? Please describe.**

This is to track work from client side as discussed in our last design meeting:

Client side:

1.	Implement Roll back hash / CRC or some kind of hashing algorithm 
2.	Improve client recovery
3.	Provide details / signal to server – Need to work on identifying mechanisms on how to send signal back to server
4.	Telemetry changes if applicable

More details and background below.

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

Thank you for the great inputs and discussions today. Here are the follow-up items as per my notes, please let me know if I missed anything or noted down incorrectly.

Client side:

1.	Implement Roll back hash / CRC or some kind of hashing algorithm 
2.	Improve client recovery
3.	Provide details / signal to server – Need to work on identifying mechanisms on how to send signal back to server
4.	Telemetry changes if applicable

Push side:
1.	Work on identifying more resilient ways to handle 404 
2.	

Server side:
1.	Provide a standalone API or identify a way to get signal for hash
2.	Server side detection & telemetry if possible. As per the discussions so far, this is not easy and impossible to detect.

I will create work items to track these, pl. let me know if I missed anything else.

Thanks,
Raja

-- The secret to success is to work less as individuals and more as a team.

From: Raja gopal Andra
Sent: Wednesday, March 31, 2021 2:08 PM
To: Vlad Sudzilouski; Tony Murphy; Marcelo Mas; Gary Wilber; Justin Moore
Subject: Two messages with same seq# and different payload! 

Hi,

I wanted to discuss about this problem and potential ideas for improvements. I’ve also added this to tomorrow’s agenda to discuss further.

Little Background:

This is in regards to ICM’s (Incident-232650637 & Incident-233633946) that we resolved this month.
This specific issue was in the SPO side where cache code was not resilient to errors – details in Bug 1082909.
We are aware of another issue (Bug 1065102) which can cause to similar situation. From the current ICM, I 
understand that clients were able to recover automatically which is good. 

The problem is op-rollback on the server without an epoch change. I would like to discuss the
scenarios and ideas on how we can address the same.

1.	Gary / Push team - Given the transient nature of the bug above, would it be reasonable for PUSH to not immediately discard changes when it sees a 404?
2.	What's the story with recycle bin? Does epoch change when file is recovered from recycle bin?
3.	Client side detection & recovery
4.	Server side detection & recovery

One scenario we can think of for 404 error other than the two bugs identified above is – need to test this:

           Step 1: Connect to a file
           Step 2: Go offline
           Step 3: Delete -> Move to recycle bin
           Step 4: Push gets 404 & drops session 
           Step 5: Restore file from recycle bin (does epoch change?)
           Step 6: Connect again
Some ideas on approaches:

1.	Fallback in client & Push to probably retry / verify to actually check file is removed by doing a GET call
2.	Probably use the rolling hash that we discussed in one of earlier meetings
3.	Have a file property like “last restore time”, compare epoch and time of modification
4.	Any other ideas 😊

From my understanding, client seems to have good telemetry to identify and alarms to notify when this happens.
I am not sure about the same on Push side and SPO side. 

Thanks for reading thru all this and reach out if you have any queries or we can discuss further in tomorrow’s meeting as well.

Please share your thoughts / opinions / concerns / ideas.

Thanks,
Raja

-- The secret to success is to work less as individuals and more as a team.

**Comment by anthony-murphy** [comment] 2021-04-05 20:28
this is a duplicate of #5689

**Closed** 2021-04-09 00:00 UTC
Labels: resolution: duplicate
