### ISSUE TITLE
Can not insert SharedMap into SharedObjectSequence

### ISSUE THREAD

**Issue by qianfeiqianlan** [microsoft/FluidFramework#3938] opened 2020-10-14 11:41 UTC
## Describe the bug
I have the DataObject like this:
```
protected async initializingFirstTime() {
    const sequence = SharedObjectSequence.create(this.runtime);
    this.root.set("sequence", sequence.handle);
}

public async insertNode () {
    const children = await this.root.get<IFluidHandle<SharedObjectSequence<IFluidHandle<SharedMap>>>>("sequence").get();
    const map = SharedMap.create(this.runtime)
    children.insert(0, [map.handle as IFluidHandle<SharedMap>])
}
```

I definition insertNode method and try to insert children node when user typed some content.

But after init this data object and call **insertNode()**, I got the error: **initialMessages called twice**

I just wanner add SharedMap into SharedObjectSequence. Is any wrong for this case?

### To Reproduce

I reappear this issue by draft-js example, here are [commit code](https://github.com/qianfeiqianlan/FluidExamples/commit/143034e8899e71d43d153c0e36beb5a21d735e3b) and [insert-node-test branch](https://github.com/qianfeiqianlan/FluidExamples/tree/insert-node-test)

**Comment by anthony-murphy** [comment] 2020-10-14 18:25
This looks like a duplicate of #3707

**Closed** 2020-10-27 00:00 UTC
Labels: bug, resolution: duplicate
