### ISSUE TITLE
Implement automatic won't fix / closing workflow for issuer in repo

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6307] opened 2021-05-28 16:37 UTC
Background - discussion:

I got to old issues, and pretty much for every old issue (over a year, I think we have ~200 of them) I either resolve it, or ask a person if it's still needed and if there is a plan to move it forward, and add "status: no recent activity" label to it.
The bot can do the same, and close issue if there is no movement.
I know many other open source repos do it, and close issues with no activity very quickly (some - within a month).
Should we do something like that? Let's say we start with 6 month cadence. I.e. every 6 months bot would ask a question if it's still valid and if there is a plan to address it. No response within 2 weeks -> close. Response -> Wait another 6 months.

There is an agreement that we want to do it. @danielroney suggests quicker cadence.
I think we should start with 6 months, but keep reducing it slowly (to make sure engineers had a chance to adjust).

**Comment by micahgodbolt** [comment] 2021-06-01 15:12
this sounds like a great idea.

**Comment by micahgodbolt** [comment] 2021-06-01 17:30
Typically we close "no recent activity" issues after 3 days. If you want a 2 week window for closing 'stale' issues, we need a different tag like "status: stale", and we can close those after 2 weeks. Does that work?

**Comment by vladsud** [comment] 2021-06-02 16:30
Some human need to add "no recent activity" label to start the process. This issue is about no human involvement. I.e. after some amount of time (let's say 6 months) if issue was not touched, add that label to start the process.

Also IMHO 3 days for "no recent activity" & "won't fix" is too short. I've marked a lot of items with these labels on Friday, and they all got closed on Monday (long week-end), giving no time to anybody to react. If possible, we should either make it 3 business days, or increase it to 5 days or so to account for week-end and possibly long week-end.

**Comment by tylerbutler** [comment] 2021-06-02 17:46
> Some human need to add "no recent activity" label to start the process.

This was a side effect of other decisions, not the intent. We intended for "no recent activity" to be automated - that's one reason the bot removes it when the issue is updated. That said, I think it's useful to be able to distinguish between "this expired" and "someone thought about this and made a decision to ignore it." The GitHub Ui does tell you who applied the labels, but it's hard to see.

I propose we add a new "stale" label for automated expiration, and set that to **6 months.**

"no recent activity" folks can add manually, and let's **extend that to eight days before closing.** (seven plus one to be generous RE: timezones)

Aside: I like the idea of using a format like "status: \*" like we do for areas, but when I looked at our labels that format didn't seem to fit. Unless we rename some - maybe that's not too destabilizing?

**Comment by tylerbutler** [comment] 2021-06-02 17:49
Thinking about this more, what do you think about making "no recent activity" into a resolution, like we do for Won't Fix? "resolution: too old"?

**Comment by vladsud** [comment] 2021-06-02 18:03
Sounds reasonable to me.

**Comment by micahgodbolt** [comment] 2021-06-07 23:05
@vladsud i changed that 3 day to close to 5 day to close on 'no recent activity'

**Comment by micahgodbolt** [comment] 2021-06-07 23:27
Ok, and now a status: stale tag set up for anything over 180 days (easy to tweak). After 8 days of no activity, stale issues with close.

**Comment by vladsud** [comment] 2021-06-08 02:13
I noticed (by how quickly my mailbox was filled :))
Note that the bot only looks at discussion, it does not pay attention to references to other items.
For example in referenced 3677 in 6272, but bot disregards it and marks 3677 as stale.
Is there any way to count any activity against being stale?

**Comment by micahgodbolt** [comment] 2021-06-08 16:40
I can omit issues with "epic" tag.

**Comment by micahgodbolt** [comment] 2021-06-09 14:42
@tylerbutler sounds good! That's certainly closer to my original intention.

**Comment by tylerbutler** [comment] 2021-06-09 22:37
I think the original intent of this issue has been addressed so I'm closing. @vladsud feel free to reopen if I missed something.

**Closed by tylerbutler** 2021-06-09 22:37 UTC
Labels: bug
