### ISSUE TITLE
SummaryMetadataMismatch error hit many times in one doc (dataCorruption)

### ISSUE THREAD

**Issue by chensixx** [microsoft/FluidFramework#8686] opened 2022-01-07 23:05 UTC
## Describe the bug

We found one document that had multiple `summaryMetadataMismatch`  errors with 2 users, first in Dec, now in Jan.
We hope to figure out what's going on and fix the document
the docId is  `XSs2e2uC9oUVZL40Si56gGB12ZyJwRL8IGx82wfvHDE%3D`

### Logs

Logs of the errors hit in Januarary
|Data_eventName	|Data_message	|Event_Time|
|-----|--------|--------|
|fluid:telemetry:Container:Load_start	||	2022-01-06 17:55:06.7130000|
|fluid:telemetry:OdspDriver:TreesLatest_GetToken_end	||	2022-01-06 17:55:06.8010000|
|fluid:telemetry:OdspDriver:EpochLearnedFirstTime	||	2022-01-06 17:55:07.1410000|
|fluid:telemetry:OdspDriver:TreesLatest_end	||	2022-01-06 17:55:07.1490000|
|fluid:telemetry:OdspDriver:ObtainSnapshot_end	||	2022-01-06 17:55:07.1510000|
|fluid:telemetry:OdspDriver:GetDeltas_end	||	2022-01-06 17:55:07.2060000|
||fluid:telemetry:OdspDriver:CacheOpsRetrieved|	|	2022-01-06 17:55:07.2060000|
|fluid:telemetry:CodeLoad_end	||	2022-01-06 17:55:07.2430000|
|fluid:telemetry:Container:ContainerClose|	SummaryMetadataMismatch|	2022-01-06 17:55:07.2510000|
|fluid:telemetry:AttachmentBlobsLoaded	||	2022-01-06 17:55:07.2550000|
|fluid:telemetry:DeviceSpec|	|	2022-01-06 17:55:07.2560000|
|fluid:telemetry:ContainerLoadStats|	|	2022-01-06 17:55:07.2560000|
|fluid:telemetry:Container:Load_cancel	|SummaryMetadataMismatch	|2022-01-06 17:55:07.2580000|
|fluid:telemetry:OdspDriver:GetDeltas_cancel	||	2022-01-06 17:55:07.2590000|
|fluid:telemetry:OdspDriver:OpsFetch	||	2022-01-06 17:55:07.6750000|
|fluid:telemetry:Container:Load_start	||	2022-01-06 17:55:16.2360000|

**Comment by pleath** [comment] 2022-01-08 01:38
The looks like a failure that we've hit before: #8066. We haven't yet discovered a root cause.

**Comment by ChumpChief** [comment] 2022-02-08 17:32
New incident is hitting today, on docId WcGeaQ%2BQNVltH41QvEGMWA9dV%2BgXi%2BR6N4c1OB8U1Xg%3D

**Comment by ChumpChief** [comment] 2022-02-08 18:01
Reopening due to new data.

**Comment by agarwal-navin** [comment] 2022-02-23 01:41
I noticed the following in the documents that have this error:

They summarized with version 0.53 / 0.54 till sequence# X.
Then they summarized with version 0.47.1 from sequence# > X to sequence# Y.
After this, clients running later versions can't load with summaryMetadataMismatch error. The runtime sequence# is X and protocol sequence# is Y.
This is strange. It looks like the client is getting the summary from # 1 but the protocol blob is from summary in # 2.
Alternatively, we could be adding the wrong message to the metadata blob in 0.47.1. This seems unlikely because I would expect the failure to be in clients running 0.47.1 as well. But the failure happens as soon as a client with newer version opens the document.

Query for this for one of the documents:
union Office_Fluid_FluidRuntime_*
| where Data_docId == "WcGeaQ%2BQNVltH41QvEGMWA9dV%2BgXi%2BR6N4c1OB8U1Xg%3D"
| where Data_summarySequenceNumber > 2937 or Data_protocolSequenceNumber > 2937
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_end" or Data_error == "SummaryMetadataMismatch" or Data_eventName == "fluid:telemetry:Summarizer:Running:SummaryOp"
| sort by Event_Time
| project Event_Time, Data_eventName, Data_message, Data_runtimeVersion, Data_clientType, Data_sequenceNumber, Data_refSequenceNumber, Data_referenceSequenceNumber, Data_summarySequenceNumber, Data_runtimeSequenceNumber, Data_protocolSequenceNumber

**Comment by agarwal-navin** [comment] 2022-02-23 01:41
Also, the loaderVersion for # 2 in the above comment is 0.36.0. This bug be due to some incompatibility between the driver / loader versions as well.

**Comment by markfields** [comment] 2022-03-08 19:18
The alert fired again.  I'm leaving the IcM ticket active at Sev4 to dedupe future hits against. 
https://portal.microsofticm.com/imp/v3/incidents/details/293691527

This bug has had a high cost for OCEs over the last 2 months so we should prioritize a mitigation here pretty urgently.

FYI @nmsimons for triage

**Comment by agarwal-navin** [comment] 2022-03-08 19:45
Can you check if it summarized with older versions - loader 0.36.x and runtime 0.47.x?

**Comment by markfields** [comment] 2022-03-08 20:07
3 of the 5 docIds hitting this in last 30 days had the Running Summarizer log from Fluid Preview (0.36.0 loader / 0.47.1 runtime).  1 had no Running Summarizer log - i.e. the last time it summarized must have been over 30 days ago.  The remaining one had the Running Summarizer log from a not-so-old loader/runtime (0.47.1 / 0.54.3), but my suspicion is that this doc also had a summary generated on old Fluid Preview more than 30 days ago.

**Comment by agarwal-navin** [comment] 2022-03-08 20:11
This sound very similar to my analysis here - https://portal.microsofticm.com/imp/v3/incidents/details/289801053/home. Can you please take a look if these docIds are the same as I mentioned in the incident.

**Comment by markfields** [comment] 2022-03-08 20:35
Yes your analysis is great!  The problem is, we never drove to a fix or mitigation of any kind, and even though we'd like to ignore these because it's essentially an unsupported scenario, we can't because it keeps happening and draining hours of OCE time and effort and represents a significant amount of noise.  So we need to do something.

Ideas off the top of my head (none are great):
* If we can detect a more specific signature that points to the Fluid Preview corruption, update the error in code
* Keep a running list of broken doc ids, and exclude them from the monitor.  Have a super clear TSG with instructions to validate the root cause via a Kusto Query and update the list of doc ids.

**Comment by markfields** [comment] 2022-03-21 21:00
@agarwal-navinm, @sdeshpande3, @ssimic2 and I looked a little closer here and found what's going on in the configuration of 0.36 loader and 0.47 runtime.  A change to the `formMetadata` function in 0.45 (I think?) depended on the loader being somewhat recent as well - otherwise a property on `DeltaManager` would be undefined and it would fallback to fill in part of the metadata with the previous summary's value.  This is exactly what happens here, resulting in a summary with mismatched metadata between the metadata blob (incorrect) and the protocol blob (correct).

**Comment by markfields** [comment] 2022-03-23 21:37
Quick update on internal response here - We have excluded this error message from the Data Corruption monitor.  Due to the presence of these old clients and corrupted documents, we will continue to see occasional hits as people open unsupported corrupted docs.  This disqualifies this error from being useful in that monitor, which is tuned to fire for a single document hitting the error.

Follow-ups are tracked in IcM and GitHub issue(s) will be opened as-needed when going through postmortem process.

Closing this one, no additional action needed here.

**Closed by markfields** 2022-03-23 21:37 UTC
Labels: bug, msft: oce

**Comment by agarwal-navin** [comment] 2022-03-23 22:33
A little more technical details on this issue:
Background / implementation of the `SummaryMetadataMistmatch` validation:
- During summary, we write the last message that was processed in the ".metadata" blob in the `formMetadata` function. The seq# of this message is the refseq# of the summary. This is written by the client. If no message has been processed since last summary, we write the message from the ".metadata" blob of the summary that the client loaded from.
- In the snapshot downloaded from the server, there is a ".protocol" blob that contains the refseq# of the snapshot. This is written by the server.
- When loading a container, we compare these two refseq# and ensure they are the same. This is to catch issues in the server where it may write the refseq# of a different snapshot to the one that is sent to the client. This has happened before and that is why the validation was added.

Root-cause:
- The change to write the last processed message to the ".metadata" blob was added in 0.45. The message is retrieved from the delta manager which is in the loader layer.
- The last processed message property was added to delta manager in 0.37.
- So, when running runtime version >=0.45 and loader version <=0.37, the last processed message on delta manager would return undefined. The runtime falls back to writing the message in the ".metadata" blob of the summary it loaded from because it thinks no message has been processed since last summary.
- This leads to incorrect last message and refseq# in the ".metadata" blob. When a client loads from this summary, it throws the `SummaryMetadataMismatch` error.

**Comment by agarwal-navin** [comment] 2022-03-23 22:36
> Quick update on internal response here - We have excluded this error message from the Data Corruption monitor. Due to the presence of these old clients and corrupted documents, we will continue to see occasional hits as people open unsupported corrupted docs. This disqualifies this error from being useful in that monitor, which is tuned to fire for a single document hitting the error.
> 
> Follow-ups are tracked in IcM and GitHub issue(s) will be opened as-needed when going through postmortem process.
> 
> Closing this one, no additional action needed here.

This sounds fine but we should also have a plan to enable the alert back on. I am not sure what is the criteria for that is but we should at least track it and make sure its not forgotten.
