### ISSUE TITLE
Too frequent summaries without user activity: recovery not successful on first failed attempt

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6213] opened 2021-05-21 16:43 UTC
Marcelo reported too frequent summaries without doing anything with the doc.

union Office_Fluid_FluidRuntime_*
| where Data_docId == "PXZGCPl6KyU8t5PNPR6CPlrupW79zPmeFEhVmo72pGQ%3D"
| where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary_end"
| project Data_eventName, Event_Time, Data_message, Data_refSequenceNumber

Looking at telemetry, I do so something weird, for example these 3 summaries back to back:

fluid:telemetry:Summarizer:Running:GenerateSummary_end	2021-05-21T04:19:42.376Z	maxTime	1137
fluid:telemetry:Summarizer:Running:GenerateSummary_end	2021-05-21T04:19:43.685Z	maxTime	1139
fluid:telemetry:Summarizer:Running:GenerateSummary_end	2021-05-21T04:19:45.219Z	maxTime	1144

All 3 were produced by same summarizing client and it booted before first in this list, so you would expect it to have all correct data to perform summaries, but something went wrong, and it took two retries to recovery:

Here are all summary-related event in between 1 & 3:

fluid:telemetry:Summarizer:Running:GenerateSummary_end	2021-05-21T04:19:42.376Z	maxTime	1137
fluid:telemetry:Summarizer:Running:MissingSummaryAckFoundByOps	2021-05-21T04:19:42.384Z		1137
fluid:telemetry:Summarizer:Running:GarbageCollection_end	2021-05-21T04:19:42.387Z		
fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch	2021-05-21T04:19:42.42Z		
fluid:telemetry:OdspDriver:uploadSummary_end	2021-05-21T04:19:43.378Z		
fluid:telemetry:OdspDriver:uploadSummaryWithContext_end	2021-05-21T04:19:43.379Z		
fluid:telemetry:Summarizer:Running:RefreshLatestSummaryGetSnapshot_end	2021-05-21T04:19:43.682Z		
fluid:telemetry:Summarizer:Running:GenerateSummary_end	2021-05-21T04:19:43.685Z	maxTime	1139
fluid:telemetry:Summarizer:Running:SummaryOp	2021-05-21T04:19:43.791Z		1139
fluid:telemetry:Summarizer:HandleSummaryAckError	2021-05-21T04:19:44.267Z		1137
fluid:telemetry:Summarizer:Running:SummaryNack	2021-05-21T04:19:44.518Z		
fluid:telemetry:Summarizer:Running:GarbageCollection_end	2021-05-21T04:19:44.527Z		
fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch	2021-05-21T04:19:44.533Z		
fluid:telemetry:OdspDriver:uploadSummary_end	2021-05-21T04:19:45.216Z		
fluid:telemetry:OdspDriver:uploadSummaryWithContext_end	2021-05-21T04:19:45.217Z		

I think two questions that worth asking:
1. Why it failed on first attempt?
2. Why it took two (not one) retries to recover?
3. How often it happens overall and how many retries it happens overall to recover from similar conditions?

**Comment by vladsud** [comment] 2021-05-21 16:49
@arinwt, to give a bit more perspective - this file is unique as it enables certain flights in storage that modify storage behavior. They are not related to summarization (only to how data is stored on back-end) and it should not impact summarization process. But, there is always a chance for bugs, so what we are looking for is your initial assessment if issues are more likely due to existing code / logic in client or server, or this situation is unique (and in some way violates existing assumptions) and we need to take deeper look at this flight.

**Comment by arinwt** [comment] 2021-05-24 16:59
@vladsud, I can give some context here. The specific series of 3 summaries you mentioned are caused by bug #5636, and fixed in #4981, but that isn't deployed until 0.40.

The first summary in the series (ref seq 1137) was the first attempt by that summarizer client after connecting, like you said. As soon as it finished generating the summary and submitting the "summarize" op, the runtime un-paused inbound op processing, which caused the "MissingSummaryAckFoundByOps" event to fire and **incorrectly** tell the client that the summary attempt it just made failed. This is because of the bug mentioned above.

It immediately retries in "safe" mode (ref seq 1139) which is nacked by the server, probably because the first attempt actually succeeded, but the client didn't know that yet! I think this can be corroborated with the "HandleSummaryAckError" event right before.

Then, since maxTime is still exceeded, it tries to summarize again the next opportunity it gets (ref seq 1144). This one succeeds as normal, probably since the runtime internal state has recovered by this point.

To answer your questions, specifically:
1. It likely didn't fail the first attempt, but it thought it did because of the bug that is fixed in 0.40 (these events are 0.39.3).
2. First retry encountered a race condition most likely where the summarizer client state didn't update before trying to summarize again, this is a downstream issue of that same bug.
3. Just looking at that "fluid:telemetry:Summarizer:Running:MissingSummaryAckFoundByOps" event in this doc, I only see 2 occurrences. This event should fire any time this specific bug is encountered. Given the race condition from (2), it will probably result in 3 summaries (instead of 1) whenever this event incorrectly fires. It doesn't seem like that many occurrences in this file- using that docId to check- so, I suspect if there are too many summaries in this file otherwise, this specific bug probably won't cover that concern.

**Comment by vladsud** [comment] 2021-05-24 17:14
Thanks for explaining! Feel free to resolve if it's fixed already.

**Comment by arinwt** [comment] 2021-05-24 20:51
Yeah the bug itself should be fixed in 0.40, but like I said in this doc there are only 2 times that this bug occurred. So if we are observing "too many" summaries in this doc, the rest of the summary attempts should be normal.

**Closed** 2021-05-25 18:16 UTC
Labels: bug
