### ISSUE TITLE
ODSP: Add client correlation ID on Ops fetch requests 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7000] opened 2021-08-04 18:04 UTC
Based on https://github.com/microsoft/FluidFramework/issues/6997, we need to add ability for client to provide its own correlation ID on fetching ops and record it in telemetry if fetch fails.

@jatgarg, can you please help drive this? For proper implementation and all fetch requests I opened an issue here. https://github.com/microsoft/FluidFramework/issues/7175
@marcmasmsft, can you please provide your insights on how we can accomplish that?

**Comment by jatgarg** [comment] 2021-08-19 23:59
Closing this issue as dupe of https://github.com/microsoft/FluidFramework/issues/7175

**Closed by jatgarg** 2021-08-19 23:59 UTC
Labels: bug
