### ISSUE TITLE
Refactor out quorum / join + leave logic out of Container class

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8463] opened 2021-12-06 17:10 UTC
This will allow custom logic to be plugged in, for hosts like Word be able to control system messages on their own (i.e. not necessarily sequence join & leave ops, but rather have alternative ways of communicating this information).
See Epic #7993 for more details.

**Comment by vladsud** [comment] 2022-05-16 15:34
It should likely be closed in favor of the item I've just opened in ADO.

**Comment by andre4i** [comment] 2022-05-23 17:30
Duplicate of [261](https://dev.azure.com/fluidframework/internal/_workitems/edit/261/)

**Closed by andre4i** 2022-05-23 17:30 UTC
