### ISSUE TITLE
Summary telemetry alerts and KPIs

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#2075] opened 2020-05-06 18:55 UTC
We already have some dashboards and queries for tracking summary health, but we should take the next step and have alerts around these KPIs to get proactive on these types of issues.

It may take a few iterations to figure out the exact thresholds for bad scenarios, but it should be possible to get ahead of docs that aren't summarizing, etc.

Some ideas:
- docs that are failing to summarize; for example "Summarizing_cancel" events
- long trail of ops since last successful summary (as tracked by summarizer)
- fallback long trail of ops since snapshot we loaded from

**Comment by markfields** [comment] 2020-09-16 21:30
Closing as dupe of https://github.com/microsoft/FluidFramework/issues/2010, I copied Arin's original comment into that issue

**Closed by markfields** 2020-09-16 21:30 UTC
Labels: telemetry
