### ISSUE TITLE
Stress: `summaryNack: Failed to summarize the document (resourceModified).`

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8668] opened 2022-01-05 22:40 UTC
There are two issues here. One is the duplicate logging of the error, the other is the error itself. This is likely related to #8080 
fluid:telemetry:Summarizer:Running:SummaryNack	
fluid:telemetry:Summarizer:Running:Summarize_cancel

```
summaryNack: Failed to summarize the document (resourceModified).
Error
    at SummaryGenerator.summarizeCore (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/summaryGenerator.js:228:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by vladsud** [comment] 2022-06-23 21:51
Two events (nack and cancel) are actually by design - I want to be able to count nacks, it's useful to have it as separate event as number of them should not be high. Summary can fail for any reason

As for error itself - that looks like same issue as 409 (coherency failure). SPO will fail any operation on a file if concurrent operation modified file. We had a lot of debates about it and I've convinced Marcelo that's storage problem (or limitation) - there is not much reason for client to retry with exactly same payload. So they have their own retry loop not to return us these errors, but they have a limit of 5 retries - occasionally it will who up in this form or another form. As long as number of them is small, I do not care that much. And we continuously looking at telemetry all-up to make sure we are not missing cases like that.

So closing, as I'm not sure there is any action here.

**Closed by vladsud** 2022-06-23 21:51 UTC
Labels: bug, src: stress tests, ado
