### ISSUE TITLE
Package only sha256 with odsp-driver

### ISSUE THREAD

**Issue by pragya91** [microsoft/FluidFramework#6979] opened 2021-08-03 20:44 UTC
## Describe the bug
Importing @fluidframework/odsp-driver package brings in dependency for all kinds of sha hash algorithms - sha512, sha1, sha384 etc., even though odsp driver only uses sha256 utility.

See image below generated though a bundle analyzer tool:
![image](https://user-images.githubusercontent.com/6341179/128082623-caa3cd96-1b23-439a-bc7d-ff30e5dbace4.png)

### To Reproduce
1. Import @fluidframework/odsp-driver to any of your project
2. Use [webpack-bundle-analyser](https://www.npmjs.com/package/webpack-bundle-analyzer) to see the dependencies imported along with odsp-driver.

### Expected behavior
Only sha256 should be get packaged with odsp-driver package.

**Comment by heliocliu** [comment] 2021-08-12 23:36
dupe of the other odsp-driver bundle size bug

**Closed** 2021-08-12 23:35 UTC
Labels: bug
