### ISSUE TITLE
Docs Site Search - support full text search

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#2210] opened 2020-05-15 22:50 UTC

**Comment by markfields** [comment] 2021-06-12 00:44
@tylerbutler - I mean, this feels important still, but not sure how/when this would be done.  I'll let you decide if we should let it expire (well, manually close at this point) or want to keep it on the backlog.

**Comment by tylerbutler** [comment] 2021-06-14 21:37
@markfields Yes, this is important. I've put it on the list for July.

**Comment by tylerbutler** [comment] 2021-11-16 18:36
Dupe of #8012.

**Closed** 2021-11-16 18:35 UTC
Labels: documentation, area: website
