### ISSUE TITLE
Improve how errors are returned from container functions

### ISSUE THREAD

**Issue by jbissat** [microsoft/FluidFramework#6315] opened 2021-05-28 22:37 UTC
Currently attach throws when called on a closed container. This isn't necessarily a problem for the host, but it gets reported as an error in our reliability scores. The host can check the string of the message to ignore this, but this is likely not the best approach (looking for a string of "0x0d5" for instance).

We could have a better system for returning errors (than having to look up the error string). Angel suggested defining the attach function as undefined in certain states (not loaded, closed)

Tagging @anthony-murphy , @jvoels (cannot find Angel Maldonado, will forward this link when created):

"If we define the attach method in the interface as possibly undefined the developers will be "forced" to understand the cases in which the method can be in this state and not call it if it doesn't exist.
In the fluid side we would then change the object to not have any of these methods as soon as its state changes to Closed (or any other state with similar consequences)"

**Comment by jvoels** [comment] 2021-06-01 14:01
The core feedback here seems to be "error/exception scenarios should have better usability".

I think of the case we're looking at as "Invalid Operation Exception - Cannot call method 'attach' on closed container" - to which the framework is likely entitled to leverage.

I don't actually agree at a glance with setting methods to undefined to indicate they cannot be called. I would think this has consequences of same ultimate issue (a bug, is somewhere) but worse stack traces for whoever is having to investigate. In this scenario the consumer of the framework needed to not call attach on a closed container, instead it need to run through intelligent handling of the unexpected state of affairs overall and act accordingly. If the method had simply been undefined and the consumer of the framework makes the same mistake, it's still an error, it just looks different.

It sounds like the codes like "0x0d5" are a 'by design' facet of the framework. If that's true, then we do need to establish the location of documentation, and complete it, that is the handbook of what to approach having that error. If the framework choose to use a code instead of descriptive message, then the semantics of that error code are just moving elsewhere - the _elsewhere_ needs to be provided. This is a minimum bar.

I think further discussion past that minimum bar could be centered around if we can give structure to the error codes. So if we want '[code]' instead of '[DescriptiveString]' - then are there some type system and identifier semantics help we can use to make it more usable?

**Comment by anthony-murphy** [comment] 2021-06-01 17:57
short codes are used by asserts. This probably shouldn't be an assert, as I don't want consumers coupling to specific short codes. 

If we just change this to an Error with a message like you call out above would that be enough?

**Comment by An631** [comment] 2021-06-01 19:31
The problem I would like us to find a solution to is how do we make it clear to implementors that these attach calls might fail if done in a closed container. The solutions I've heard so far are these:

1. We document this behavior and explain how things need to be done by developers to avoid the problem. The **main drawback** of this is that if the developer doesn't check this documentation, then the bug might be introduced.
2. We make the definition of the interface be closer to its actual behavior. If .attach cannot (or should not) be called when the container is closed, then we should not expose the method when the container is in this state and make the developer aware that the .attach method can be undefined. This automatically forces the implementor to check for the attach method before trying to access it.

I personally prefer approach 2 as it reduces the possibility of mistakes and is not dependent on developers following the documentation.

**Comment by markfields** [comment] 2021-06-30 19:28
Following.  I'm doing a lot of thinking about how we propagate errors through/out of the framework.

**Comment by markfields** [comment] 2021-06-30 19:36
Documentation + a nice error object seems like a fair outcome to me for both `attach` and the general case this issue seems to be about.

That said, encoding this kind of thing in the API signature is always nice.

About `attach` in particular, @An631's idea seems fine, or something like `attach` doesn't throw but rather returns `false` in cases like this.

**Comment by markfields** [comment] 2021-07-09 21:43
Hey all - please take a look at the design I've landed on, here: #6676
_(Removing the Design Required tag, FYI @vladsud, @curtisman)_

As pertains to the specific case for attach, my plan is to switch the assert(s) to `if` checks that throw an error with a meaningful `errorType` and `errorCode`, something `InvalidOperationError` and `CannotAttachClosedContainer` respectively.

Tony and I have been discussing a brighter future where our APIs do less throwing and more returning of error codes, but that is very hypothetical.  Just sharing the directional thought.

**Closed** 2021-08-05 20:58 UTC
