### ISSUE TITLE
The @fluidframework/test-runtime-utils throw an error about " Module not found: Error: Can't resolve 'assert'"

### ISSUE THREAD

**Issue by zhonglin94** [microsoft/FluidFramework#11709] opened 2022-08-29 02:52 UTC
## Describe the bug
The @fluidframework/test-runtime-utils throw error about " Module not found: Error: Can't resolve 'assert'"
![image](https://user-images.githubusercontent.com/32061513/187112907-415d6b75-1804-4fd8-bf21-3b90ce105f1a.png)

### To Reproduce
1. ng new an empty Angular 14 project
2. npm install with the following dependencies:

> 
> "dependencies": {
>     "@fluidframework/azure-client": "^1.0.2",
>     "@fluidframework/test-runtime-utils": "^1.2.4",
>     "@fluidframework/tinylicious-client": "^1.2.4",
>     "fluid-framework": "^1.2.4",
>     "@angular/animations": "^14.0.0",
>     "@angular/common": "^14.0.0",
>     "@angular/compiler": "^14.0.0",
>     "@angular/core": "^14.0.0",
>     "@angular/forms": "^14.0.0",
>     "@angular/platform-browser": "^14.0.0",
>     "@angular/platform-browser-dynamic": "^14.0.0",
>     "@angular/router": "^14.0.0",
>     "rxjs": "~7.5.0",
>     "tslib": "^2.3.0",
>     "zone.js": "~0.11.4"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^14.0.4",
>     "@angular/cli": "~14.0.4",
>     "@angular/compiler-cli": "^14.0.0",
>     "@types/debug": "^4.1.7",
>     "@types/jasmine": "~4.0.0",
>     "jasmine-core": "~4.1.0",
>     "karma": "~6.3.0",
>     "karma-chrome-launcher": "~3.1.0",
>     "karma-coverage": "~2.2.0",
>     "karma-jasmine": "~5.0.0",
>     "karma-jasmine-html-reporter": "~1.7.0",
>     "typescript": "~4.7.2"
>   }

3. Import the 'InsecureTokenProvider' in the app component as the following:

> 
> import { Component } from '@angular/core';
> import { InsecureTokenProvider } from '@fluidframework/test-runtime-utils';
> 
> @Component({
> 
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.scss']
> })
> export class AppComponent {
>   title = 'test-fluid-upgrade';
> 
>   token = new InsecureTokenProvider('', {
>     id: ''
>   });
> }

4. run command npm start in the terminal
5. Then you will see the error and the project fails to start

### Expected behavior
The project should start without any error.

**Comment by tylerbutler** [comment] 2022-09-08 16:41
@zhonglin94 Thank you for filing this issue! I think it is a duplicate of #11350.

**Closed** 2022-09-11 18:02 UTC
Labels: bug, resolution: duplicate, community-contribution
