### ISSUE TITLE
"works in detached container" test in blobs.spec.ts logs 0x204 for tinylicious

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9287] opened 2022-03-02 02:02 UTC
"works in detached container" test expects error 0x202 in the `itExpects` block. However, that error is only thrown by the local driver. Tinylicious throws 0x204 error which is logged and reported as an error:

<html>
<body>
let buildId = 52922;

office_fluid_ffautomation_error
| where Event_Time > ago(7d) and Data_hostName == "@fluidframework/mocha-test-setup"
| where Data_branch == "refs/heads/main" and Data_buildId == buildId and Data_driverType == "tinylicious"
| where Data_message == "0x204"
| summarize count() by Data_errorType, Data_eventName, Data_message, Data_reason

Data_errorType | Data_eventName | Data_fluidErrorCode | Data_message | Data_reason | count_
-- | -- | -- | -- | -- | --
genericError | fluid:telemetry:Container:ContainerClose |   | 0x204 |   | 4

</div>
</body>
</html>

**Comment by anthony-murphy** [comment] 2022-03-02 19:58
i think this is a duplicate of #9039

**Closed** 2022-03-02 23:53 UTC
Labels: triage
