### ISSUE TITLE
Prod [0.50]: assert(this.attached, 0x188 /* "Local channel must be attached when processing op" */);

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8305] opened 2021-11-17 17:26 UTC
OCE folks, can you please glance and assess severity / potential case for latest regression?

Looking at the errors from latest build:

> union Office_Fluid_FluidRuntime_Error
| where Data_loaderVersion contains "0.5"
| where Event_Time > ago(2d)
| summarize count() by Data_eventName, Data_error

I see new error that I do not remember seeing before:

fluid:telemetry:Container:ContainerClose	0x188	14

This is    

public processOp(message: ISequencedDocumentMessage, local: boolean, localOpMetadata: unknown): void {
        assert(this.attached, 0x188 /* "Local channel must be attached when processing op" */);

**Comment by vladsud** [comment] 2021-11-18 01:00
It would be great to understand how we can raise more clear error pointing to the core of the problem.

**Comment by agarwal-navin** [comment] 2021-11-18 16:55
This is a regression caused by this change - https://github.com/microsoft/FluidFramework/pull/7917. It removed the check for container detached state before attaching graph.

When the container is detached, the graph of data stores / DDSs should not be attached. This should happen when the container gets attached.

With this change, a data store attaches its graph in detached container as well.  After this, any DDS (channel) that is created in this data store while the container is detached will not be attached. I can repro this in tests.

**Comment by agarwal-navin** [comment] 2021-11-18 16:56
The whole state machine around attach state and graph attach state is very complicated. We should look into simplifying this.

**Comment by agarwal-navin** [comment] 2021-11-19 00:05
This has been fixed in 0.50 and 0.51.

**Closed by agarwal-navin** 2021-11-19 00:05 UTC
Labels: bug

**Comment by agarwal-navin** [comment] 2021-11-19 01:14
Another worrying thins here is that a DDS that is not in attached state was visible on remote clients. This should never happen.

**Comment by agarwal-navin** [comment] 2021-11-19 01:20
Created an issue to track this - https://github.com/microsoft/FluidFramework/issues/8348
