### ISSUE TITLE
User reports one tab not propagating data to another tab when same document is opened in both tabs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3896] opened 2020-10-09 21:16 UTC
[Teams thread](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1602193411638?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1602193411638&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Bugs%20%F0%9F%90%9B&createdTime=1602193411638)

There are too many disconnects:

Office_Fluid_FluidRuntime_Performance
| where Data_docId == "Q50eQ%2FtQmJY8Re0Fc8udsPH621ini7LkRsI9ki12AJE%3D"
| where Session_Id == "1e332ee1-d833-4f00-ac2e-b0b7d66ee854"
| where Data_eventName contains "Connected"
| project Event_Sequence, Event_Time, Data_eventName, Data_clientType, Data_reason, Data_clientId

Two key observations:
1. I believe we still have a but that does not tell us real reason for disconnect (transport close is socket.io reason, we have to have server reason, unless indeed connection is so unreliable).
2. I believe we have telemetry somewhere telling us how many ops are not submitted (local) at the time of establishing connection - that number, if not zero all the time, would tell us if any ops are going through.

**Comment by ChumpChief** [comment] 2020-10-09 23:16
Update 10/9: Not yet looking at this bug, currently investigating other critical issues.  Probably will get to sometime next week pending new incoming critical issues.

**Comment by vladsud** [comment] 2020-10-10 17:00
Out of 295K disconnects over last 30 days, we have these 

Disconnect: transport close  43152      (14.5%)
Disconnect: client closing connection	8965 (3%)

In both cases we do not have real socket connection, I think. I.e. there should be higher-level reason for closing connection, not websocket transport just being closed. I.e. either socket.io reason or even better - PUSH / client reason
I believe we are losing data (not reporting correctly) on reason of connection somewhere

**Comment by vladsud** [comment] 2020-10-10 17:05
@GaryWilber, there is some bug on client side not allowing us to see real reason for disconnects.
Any chance you can go through some number of clientIDs in the query in description of this issue and tell what was the real reason client kept disconnecting every 2-3 minutes?

**Comment by vladsud** [comment] 2020-10-10 17:09
There is fluid:telemetry:OpPerf:ConnectionSpeed event after each connection, so client believes it is getting up-to-date (i.e. observes all ops available at the time of connection). Does not really match Vikas' description of either of the clients. :(

**Comment by vladsud** [comment] 2020-10-12 02:29
One interesting observation: we should never ever get "client closing connection" reason for disconnect.
This is coming from OdspDocumentDeltaConnection.disconnect() that is called in these 3 workflows:
1. From DeltaManager (through DeltaConnection.close() flow), but we already emitted disconnect event with real reason and reset this.conneciton to undefined to protect against reentrancy.
2. From various early handlers installed via addConnectionListener() that should be removed on successful connection. If any of these handlers is called , that means we do not have connection, i.e. no DeltaManager handlers had a chance to be installed and produce this telemetry.
3. "error" handler -  "error" event is raised and that should be the reason for "disconnect",, events raised from disconnect() called later should not reach DeltaManager.

None of these should result in this message ever getting to telemetry.

**Comment by vladsud** [comment] 2020-10-12 03:10
There are ~1500 DeltaConnectionError events, which is path going through # 3 above - way less than number of "client closing connection" disconnects.
So # 2 is the most likely reason.

**Comment by ChumpChief** [comment] 2020-10-19 22:53
One of the two sessions:
| where Data_loaderId == "f31590e7-eb18-41c0-aa8a-6ca7cfac0241"
| where Data_containerId == "5eafdb54-c060-49bf-aa2d-bf6a36fcdd99"

**Comment by ChumpChief** [comment] 2020-10-28 20:24
Putting names on the clients:

- Client A is the one NOT displaying the changes, that after a refresh successfully loads and gets up to date.
- Client B is the one producing the changes.  After Client A refreshes, Client B starts showing a yellow bar.

We know Client B's changes made it to the server because Client A eventually gets up to date.  So I'm hypothesizing that the issue is on the receiving side of Client A.

The yellow bar is also particularly suspicious since it's triggered by a separate client.  If Client A was the summarizing client then summarizing duty might have passed to Client B upon the refresh, this is the main way that I know of that Client A's refresh would have had a substantial effect on Client B though I don't know specifically why it would have caused a yellow bar.

If Client A was the summarizer, one hypothesis is that it got stuck paused during summarization.  This would explain no further updates coming in.  I don't have a hypothesis for why it would get stuck though, will look further in this direction.

**Comment by ChumpChief** [comment] 2020-10-29 00:18
No obvious leads here, so closing for now (we'll open a new instance if/when it hits again).

Going with the hypothesis above, I put up #4151 which I don't think is related but would give us a more obvious error if it happens to be.  The pause/resume logic has also changed recently with #4086 which may also have an effect.

**Closed by ChumpChief** 2020-10-29 00:18 UTC
Labels: OCE, bug
