### ISSUE TITLE
Second user failing to get to "connected" state

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#3444] opened 2020-08-31 19:00 UTC
Repro:

1. Go to https://github.com/microsoft/FluidHelloWorld and follow the getting started instructions.
2. Get the example started
3. open browser to new tab. (don't click the roll button)
4. open the same instance in a new tab.

Expected:
The second user is connected and can edit the die

Result:
The second user never makes it to a "connected" state and does not send ops.

**Comment by vladsud** [comment] 2020-09-08 19:55
Yes and no.
Yes, we have a race. And no, it's not caused by this code - same thing can happen on 2nd, 3rd connection - no difference
There can be always outstanding fetch request to storage that can bring ops faster than process of establishing connection.
So the fix to the race issue is not here, it's in looking back and using quorum to understand if self-join was already processed by the time connection is fully established.

**Comment by vladsud** [comment] 2020-10-13 23:12
Main issue has been addressed in above mentioned PR, but I've kept the bug open to take a look at the rest of discussion (i.e. attachOpHandler logic)

**Comment by vladsud** [comment] 2021-05-27 23:41
I believe all problems mentioned in this thread are already addressed.

First, the main problem is fixed:

        // Check if we already processed our own join op through delta storage!
        // we are fetching ops from storage in parallel to connecting to ordering service
        // Given async processes, it's possible that we have already processed our own join message before
        // connection was fully established.
        // Note that we might be still initializing quorum - connection is established proactively on load!
        if ((protocolHandler !== undefined && protocolHandler.quorum.getMember(details.clientId) !== undefined)
            || connectionMode === "read"
        ) {
            this.setConnectionState(ConnectionState.Connected);
        }

Second, the code around op pre-fetching has been changed by me multiple times and no longer resembles what this issue references :)

**Closed by vladsud** 2021-05-27 23:41 UTC
Labels: area: runtime, bug
