### ISSUE TITLE
polyfills error when upgrading @fluidframework/test-runtime-utils 

### ISSUE THREAD

**Issue by pashrafi1** [microsoft/FluidFramework#12136] opened 2022-09-26 21:57 UTC
## Describe the bug
I am using fluid framework with Azur Client in Angular 13 -  When I upgrade @fluidframework/test-runtime-utils to any version after 0.59.4002 I'm getting the following error:

/node_modules/@fluidframework/test-runtime-utils/dist/validateAssertionError.js:8:17-34 - Error: Module not found: Error: Can't resolve 'assert' in '..\src\angular\node_modules\@fluidframework\test-runtime-utils\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }

### Expected behavior
I should be able to upgrade to newer version without issue

**Comment by tylerbutler** [comment] 2022-10-05 16:34
Duplicate of #11350. This is fixed in 1.2.6.

**Closed** 2022-10-08 18:02 UTC
Labels: bug, resolution: duplicate, community-contribution
