### ISSUE TITLE
Add support for simple resolve of ODSP URLs to odsp-driver

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4354] opened 2020-11-16 20:49 UTC
The ODSP driver recently took code from an internal repo that was widely used for resolving ODSP urls to enable some new sharing performance optimizations. This code was put in the ODSPURLResolver2. As part of this code move, the code in this repo, ODSPUrlResolver2 now takes in a required argument to the constructor around sharing link tokens. This breaks a common flow where hosts try to resolve the ODSP url and do not need to do anything with respect to sharing. 

Here is an example of code that Teams used to have with the internal resolver that now is broken with the FF resolver.

 const resolver = new OdspUrlResolver();
  const details = await resolver.resolve({ url: fileUrl });
  if (!details || !details.driveId || !details.itemId) {
    throw new Error(`Couldn't parse fluid file url: ${fileUrl}`);
  }

**Comment by jatgarg** [comment] 2020-11-17 01:44
Duplicate of https://github.com/microsoft/FluidFramework/issues/4338

**Closed by jatgarg** 2020-11-17 01:44 UTC
Labels: bug, triage
