### ISSUE TITLE
Intervals don't seem to go back to their previous positions after an undo operation

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#11269] opened 2022-07-25 16:51 UTC
If an interval's start and end offset is @15 in the document and if user deletes the text from @[10 - 20] and does an undo immediately. And now if the interval's start and end offset is queried, it will be @20 instead of @15. 

The ask from this bug is to make interval positions undo friendly. The intervals should be back at their previous position instead of being at the end of inserted text after an undo operation. In the above example, after the undo operation the interval's start and end offset should be @15 instead of @20.

The following are the API being used to created intervals, delete text and query the interval position

APIs to create intervals

> const sharedIntervalCollection = sharedString.getIntervalCollection(intervalType);
> const sharedInterval = sharedIntervalCollection.add(startOffset, endOffset, IntervalType.SlideOnRemove, properties);

APIs to delete text

> sharedString.removeText(startOffset, LengthOfDeletedText);

APIs to get interval position

> const sharedIntervalCollection = sharedString.getIntervalCollection(intervalType);
> const sharedInterval = sharedIntervalCollection.getIntervalById(intervalId);
> To get start position: sharedInterval.start.toPosition()
> To get end position: sharedInterval.end.toPosition()

**Comment by curtisman** [comment] 2022-07-25 21:28
@Abe27342 FYI.

**Comment by Abe27342** [comment] 2022-08-10 20:29
Hi @amruth-ms--thanks for the report. I looked into this just now as well as the other merge-tree undo/redo situation you wondered might be related.

The behavior you describe is as designed: sequence and merge-tree don't have built-in notions of undo or redo, so there's no way to reasonably expect them to revert reference slides (even via intervals) when a segment delete gets reverted.

However, this is certainly a scenario we want to support! The exposed APIs on merge-tree and sequence should make it possible to implement the behavior you want in your undo-redo logic. I'm planning on updating the example undo-redo handler for sequence to do this (sneak preview [here](https://github.com/microsoft/FluidFramework/commit/d68814cbf9077cd2fd93e26004020b507271fe20)). The gist of it is that on segment remove, you can inspect any removed segments for refs you might want to restore:

```typescript
                    if (event.deltaOperation === MergeTreeDeltaType.REMOVE) {
                        current.refsToRestore = Array.from(range.segment.localRefs ?? []).map((ref) => ({ ref, offset: ref.getOffset() }));
                    }
```

Then, in your revert logic, you can restore them in-place by sliding like so:

```typescript
                            if (insertSegment.localRefs === undefined && tracked.refsToRestore!.length > 0) {
                                insertSegment.localRefs = new LocalReferenceCollection(insertSegment);
                            }
                            for (const { ref, offset } of tracked.refsToRestore!) {
                                ref.callbacks?.beforeSlide?.();
                                insertSegment.localRefs?.addLocalRef(ref, offset);
                                ref.callbacks?.afterSlide?.();
                            }
```

There are still some things I need to work out in that example (you can see the sneak preview has a few TODOs), but the above code should be pretty close to what you want. Hopefully that's enough to unblock you while I sort out the details in the example implementation.

**Comment by amruth-ms** [comment] 2022-08-10 22:09
Hi @Abe27342 . Thank you very much for your response :) . I will try the approach you suggested.

**Comment by amruth-ms** [comment] 2022-08-12 16:33
Hi @Abe27342 , I tried the solution to make intervals undo friendly. I am putting a couple of questions I had when I tried the solution below. Could you please let me know your thoughts on them?

1. We are currently using Fluid version 1.2.0. In that version I don't see `addLocalRef` method having two parameters. It just has one parameter with type `ReferencePosition`. So, in our revert code, I could not do `insertSegment.localRefs?.addLocalRef(ref, offset)`. I wanted to check if `addLocalRef` method has any recent changes and will be released in a new Fluid version and accepts two parameters instead of just one?

2. I was wondering if the solution to make intervals undo friendly will make intervals positions to be in sync across different clients? For example, there are two clients(client1 and client2). client1 inserts an interval with same start and end position @15. Now client1 deletes text in range @[10 - 20] and immediately does an undo. Client1 will be able to restore the interval start and end positions to be @15 as it stores the references when deleting the text and will restore in its revert logic when an undo operation is done. But client2 will see the client1's undo operation just as a normal insertion of text and it will not have a chance to restore interval positions properly. So eventually I am thinking client1 will have its interval start and end positions @15 but client2 will have its interval start and end position @20. Just wanted to check if my understanding is right in this scenario.

**Comment by Abe27342** [comment] 2022-08-15 17:03
I remembered that our original plan here was to use the `changeInterval` event on `IntervalCollection` to power this. In order for that to work, one needs the changes currently checked into `next`. But I don't think it makes sense to add the alternative query for doing this that I described above, if it's going to be immediately deprecated (it's not too much code, but it does add an extra prop to each local reference that's part of an interval collection)

I'm still going to confirm that the changes in `next` make this reasonable and update the framework undo-redo handler demonstrating how one can do that.

**Comment by Abe27342** [comment] 2022-08-15 18:56
The changes in next do help, but they're not enough and IMO provide a worse experience than my previous proposal. The problem is that by the time the interval slides, the local op that caused such a slide has already been acked. This means there's basically no easy way to infer the correct place to restore the intervals to (in contrast to the above approach, where we know the exact segoff to undo the change). With a complex state machine and exposing additional query APIs on client/sequence, it's technically possible, but seems a lot easier to just expose the query API. I'm going to proceed forward with that, and I'll link a "close but not quite" commit demonstrating the issue with doing it based on changes.

**Comment by amruth-ms** [comment] 2022-08-16 22:19
Hi @Abe27342. Thank you very much for your detailed explanation and my apologies for the delayed response. I think the I get the gist behind the first approach (i.e, using the `intervalFromEndpoint(endpoint: LocalReferencePosition): SequenceInterval` query API and restore the interval interval positions after undoing a text deletion). But it looks like there is one other solution by using `changeInterval`. I am not sure if I fully understand this approach and the following statement

> I remembered that our original plan here was to use the `changeInterval` event on `IntervalCollection` to power this. In order for that to work, one needs the changes currently checked into `next`.

I am thinking, when a deletion of text happens and if there were intervals inside the text before getting deleted, the solution is to first call `changeInterval` API to change interval positions and then delete the text. So that when undo operation is done, first the deleted text will be put back and then we undo the change the happened because of the `changeInterval` API. For example, if an interval's start and end positions were @15 and if a user deletes the text from @[10,20]. We first call `changeInterval` API, to change the intervals start and end positions to be @10. And now we delete the text from @[10,20]. Now, if user does an undo operation, we first put back the deleted text from @[10,20] and undo the change that caused by `changeInterval` API call during the deletion (i.e, putting back the interval's start and end positions @15 now). I have a feeling that I totally mis-understood the solution. Very sorry if I did. Please let me know if I don't have the correct understanding. 

And we are planning to add undo support for intervals only in our code after we have access to the changes present in this PR(https://github.com/microsoft/FluidFramework/pull/10966). We will need the changes in this PR to implement undo/redo mechanism for intervals, as the APIs in this PR provide us the previous information of intervals(like previous properties when interval properties are getting changed or previous position when interval position is getting changed). We will likely be adding the support(if needed) for making intervals go back to their previous positions after a deletion of text operation is undone, after having access to the changes present in https://github.com/microsoft/FluidFramework/pull/10966.

**Comment by Abe27342** [comment] 2022-08-17 16:47
> I am thinking, when a deletion of text happens and if there were intervals inside the text before getting deleted, the solution is to first call changeInterval API to change interval positions and then delete the text. So that when undo operation is done, first the deleted text will be put back and then we undo the change the happened because of the changeInterval API. For example, if an interval's start and end positions were @15 and if a user deletes the text from @[10,20]. We first call changeInterval API, to change the intervals start and end positions to be @10. And now we delete the text from @[10,20]. Now, if user does an undo operation, we first put back the deleted text from @[10,20] and undo the change that caused by changeInterval API call during the deletion (i.e, putting back the interval's start and end positions @15 now). I have a feeling that I totally mis-understood the solution. Very sorry if I did. Please let me know if I don't have the correct understanding.

This generally seems like it could work, though it would add overhead to what's sent over the wire (each segment removal potentially necessitates first changing a number of intervals). If you expect the number of intervals to generally be small, that's a reasonable tradeoff. Might also lead to poorer-quality merges if someone else is concurrently trying to change the endpoint. But that's probably not a big deal.

If you decide to do this, do note that in most cases intervals won't slide anymore--only if the op isn't meant to go on the undo-redo stack (so you don't actually issue a `changeInterval`) or if there's some concurrency such as someone adding an interval around where you're concurrently deleting. That's totally fine, just wanted to point it out.

**Comment by amruth-ms** [comment] 2022-08-17 17:09
> This generally seems like it could work, though it would add overhead to what's sent over the wire (each segment removal potentially necessitates first changing a number of intervals).

Agree that the approach I mentioned adds overhead and we will probably not proceed with this solution. We will most likely use the query API (like `intervalFromEndpoint(endpoint: LocalReferencePosition): SequenceInterval`) solution and restore interval positions during an undo operation. We will likely make relevant changes once we have access to the changes present in https://github.com/microsoft/FluidFramework/pull/10966 and the query API.

**Comment by Abe27342** [comment] 2022-08-18 17:47
@amruth-ms The ability to get an interval from its endpoint is checked in, so once released you should be unblocked on this issue. Since one undo-redo approach was nearly working and the issues with it seem solvable from within the undo-redo handler, I'm going to table the work to implement a proper undo-redo handle until a bit later this sprint (depending how much I get randomized, may leak into next).

In the meantime I'll leave this issue open. Let me know if you run into issues that it doesn't seem like you have the APIs to resolve.

**Comment by amruth-ms** [comment] 2022-08-18 17:55
@Abe27342 Sounds great. Thak you so much for the quick addition of interval endpoint API :)

**Comment by Abe27342** [comment] 2023-04-24 17:41
bad bot. We recently funded work on this issue. re-opening. @scarlettjlee @jzaffiro could you close once current undo-redo work is resolved?

**Comment by Abe27342** [comment] 2023-04-26 22:15
Some more context on this:

Our stance at the time this issue was opened was that we should expect customers to implement that behavior in their stack.
When the issue was originally opened, even that was infeasible since there was a lot of nonsense/not enough information in IntervalCollection's change events and a lack of an ability to go from interval endpoint to the interval.

Since then, our stance is relaxed and we're working on default support through a similar revertibles notion to what merge-tree has for text edits. It will still require hooking up the revertibles into some undo/redo management system, but the burden should be roughly what's expected from any other DDS. Scarlett and Jillian are working on this right now, and AB#3578 tracks that work internally.

**Comment by scarlettjlee** [comment] 2023-07-14 07:36
Revertibles have now been implemented that can be created from events on intervals + string.

**Closed by scarlettjlee** 2023-07-14 07:36 UTC
Labels: community-contribution, ado
