### ISSUE TITLE
ODSP Scaling: fluid:telemetry:Container:connectedStateRejected

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7016] opened 2021-08-05 16:54 UTC
Why do we see a bunch of Container:connectedStateRejected events with source = "removeMemberEvent" when container is in "Connecting" state with "write" connection?
Note: This document is at 10K max ops, so it can't send any ops.
It's possible that server removes this client from quorum before sending nack? Even before client sent an op?
Seems weird, we need to get to the bottom of it and ensure that telemetry flags only cases that are important.
Also, should this event be an error? I found this case by accident, it seems like it should be an error in a sense that we should be looking at these cases, even though we do expect some number of them in normal flow. Once we are sure it's reasonable, we can convert it to non-error.

[Logs](https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F93543f02-938d-4016-9d15-9cc4329b7033%2FresourceGroups%2FRegressionPrevention%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FFluidClient/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0XNsQ0CMQxG4Z4pTEpGuJ4JmMAkPyLS2Ua2AwpieK66a58%252B6dURaXJ9QzPo9KPPEw66UDVN7hpU4G5eiLVt%252BXz0xzp6WxIrBOlzuQ0R9v7Fjg%252BbZiSss2yHME%252B6T8ouiGR5UUPUPztPLY%252BIAAAA/timespan/P1D)

customEvents 
| where customDimensions.containerId == "4fda1baa-46c2-495f-bbe0-9183eca77fa1"
| project timestamp, name, customDimensions.error, customDimensions.connectionMode, customDimensions.fetchReason, customDimensions.source
| order by timestamp asc

  | 8/5/2021, 5:37:43.658 AM | fluid:telemetry:Container:ConnectionStateChange_Connecting |   | write |   |   |  
  | 8/5/2021, 5:37:43.659 AM | fluid:telemetry:DeltaManager:enqueueMessages |   |   |   |   |  
  | 8/5/2021, 5:37:44.009 AM | fluid:telemetry:OdspDriver:OpsFetch |   |   |   |   |  
  | 8/5/2021, 5:37:44.010 AM | fluid:telemetry:OdspDriver:GetDeltas_end |   |   |   |   |  
  | 8/5/2021, 5:37:44.011 AM | fluid:telemetry:Container:connectedStateRejected |   |   |   | removeMemberEvent |  
  | 8/5/2021, 5:37:44.013 AM | fluid:telemetry:OdspDriver:CacheOpsRetrieved |   |   |   |   |  
  | 8/5/2021, 5:37:44.014 AM | fluid:telemetry:OpPerf:ConnectionSpeed |   |   |   |   |  
  | 8/5/2021, 5:37:44.015 AM | fluid:telemetry:Container:OpsSentOnReconnect |   |   |   |   |  
  | 8/5/2021, 5:37:44.015 AM | fluid:telemetry:Container:ConnectionStateChange_Connected |   | write
  | 8/5/2021, 5:37:44.131 AM | fluid:telemetry:Container:ConnectionStateChange_Disconnected |   |   |   |   |  
  | 8/5/2021, 5:37:44.134 AM | fluid:telemetry:Container:ContainerWarning | Nack: Submit a summary before inserting additional operations

**Comment by jatgarg** [comment] 2021-08-10 18:40
@vladsud We record connectedStateRejected event in case somebody applied for "Connected" state but it got rejected due to some reason. 1 thing is that I added this event so that we can have better telemetry to determine the root cause of any issue related to data corruption related to ordering service. We will remove that in few releases. 
We have 3 sources to reach to this event:
1.) We receive join message. But it can get rejected in case we are waiting for leave event and timer is running. Source should be "addMemberEvent".
2.) When the timer goes off(waiting for leave), and we haven't yet received the join op maybe. Source would be "timeout".
3.) When the leaveMember event is received, and we haven't received the join op. In that case source would be "removeMemberEvent". So it is normal we received this event when the next client is in connecting state and we received leave of previous client and we recorded this event because we haven't received the join op for newer client yet. So when we get the join op of current client, we will not reject the connected state and move to it.

**Comment by jatgarg** [comment] 2021-08-10 19:01
Ex:
1.) ClientId = x and it gets disconnected.
2.) New pending client is y (we are in connecting state). At this time the ClientId would still be X until we receive joinop for y.
3.) At this time, we receive leave for x which leads to this state which is totally normal. So resolving this issue.

**Closed by jatgarg** 2021-08-10 19:01 UTC
Labels: bug
