### ISSUE TITLE
[MFS] Needing too many ops to reflect changes in the data store state

### ISSUE THREAD

**Issue by sgarapati07** [microsoft/FluidFramework#8676] opened 2022-01-06 20:51 UTC
## Describe the bug

When the content of the blob changes in the snapshot, the changes aren't being reflected in the latest snapshot till a lot of operations are being made. I waited for about a minute without making any new ops and nothing happens when re-summarization happens. Also, I performed a few ops like around 10 and still nothing happened. Its only when I perform about 25 to 30 ops that I start seeing what I want to see in the snapshot. This is in regards to the search blob ( _search/01 ) and the contents of it in the snapshot. 

### To Reproduce

- Run this https://office.visualstudio.com/OC/_git/MfsSDK?version=GBsgarapati/podSearch&path=/examples/mfs-client-prod example in MFS repo
- Select pick a pod file and navigate to Communication site -> .appdata -> searchPod6.pod.
- Go to network tab in the developer tools and filter using latest snapshot and copy, paste the snapshot object into a text editor to see the summaries.

### Expected behavior
Search blob updates to show up with the next resummarization that is, after 5 seconds or so without me having to perform one too many ops for new changes to be reflected.

**Comment by vladsud** [comment] 2022-01-08 20:41
This is by design. Summarizing heuristic tries to balance sending too many summaries vs. keeping too many trailing ops.
@pleath can comment on actual logic, but if you have a single trailing op, and no activity, I think it will take a minute util new summary will be posted. And only if there is a client who is "write" client (which is usually the case in scenario you describe, but not given). If client just opened file for reading, then we are not making summaries, as we do not want to make that client "last editor" of a file.
Note that from FF perspective, it's totally normal state to have trailing ops - it's not an error state.

I think the reason you care is about search, and search is not FF concept. It's a contract between O365 system and ODSP, and FF is not involved here. Discussions about O365 components should happen in some other forum as they are not related to Fluid Framework platform (at least at the moment, as FF is not involved in implementing this contract).

**Comment by sgarapati07** [comment] 2022-01-10 23:04
Okay I got it. So, when I edit something in the data store, am I considered as a 'write' client ? If I don't edit and just open the data store, then am I only a 'read' client at that point of time ? @vladsud

**Comment by vladsud** [comment] 2022-01-11 06:05
Depends. When you open document, you get read connection and maintain read connection until some change is made in container. Latter triggers upgrade to write mode. Write mode is maintained for some time and downgraded back to read after some delay. Rinse and repeat.

**Comment by sgarapati07** [comment] 2022-01-11 18:46
okay, so its not something that we control but what fluid controls ?

**Comment by pleath** [comment] 2022-01-19 22:44
Vlad is right about the underlying heuristic. With no activity, we won't re-summarize. With low activity, we'll summarize after 1 minute.

**Comment by pleath** [comment] 2022-01-19 22:47
Closing for now, since the observed behavior seems to be by design.

**Closed by pleath** 2022-01-19 22:47 UTC
Labels: bug
