### ISSUE TITLE
view-only mode should issue "connected" event on current clientID being in audience

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#1733] opened 2020-04-07 20:48 UTC
We should also double-check that "write" mode also follows same requirements.
Once done, we should follow up and remove code on Bohemia side working around this issue.

More background:

From: Tony Murphy <Anthony.Murphy@microsoft.com> 
Sent: Tuesday, April 7, 2020 10:09 AM
To: Vlad Sudzilouski <vladsud@exchange.microsoft.com>; Tanvir Aumi <mdaumi@microsoft.com>
Subject: RE: Readonly and Audience

The change made to work around is pretty complicated for something I think should be trivial. I really don’t want all our partners to build similar logic just to find the current user:
https://office.visualstudio.com/OC/_git/74031860-e0cd-45a1-913f-10bbf3f82555/pullrequest/446248?_a=overview

From: Tony Murphy 
Sent: Tuesday, April 7, 2020 10:03 AM
To: Vlad Sudzilouski <vladsud@exchange.microsoft.com>; Tanvir Aumi <mdaumi@microsoft.com>
Subject: RE: Readonly and Audience

That would be great too. I’m not really proposing a specific solution, just that I think we need on here. Another idea I have was a “connected”-like event on the audience that fires when your client show up in the audience.

-Tony

From: Vlad Sudzilouski <vladsud@exchange.microsoft.com> 
Sent: Tuesday, April 7, 2020 9:26 AM
To: Tony Murphy <Anthony.Murphy@microsoft.com>; Tanvir Aumi <mdaumi@microsoft.com>
Subject: RE: Readonly and Audience

We can. But I think it’s even better if it’s handled as first class by server (see attached)

From: Tony Murphy <Anthony.Murphy@microsoft.com> 
Sent: Tuesday, April 7, 2020 9:11 AM
To: Vlad Sudzilouski <vladsud@exchange.microsoft.com>; Tanvir Aumi <mdaumi@microsoft.com>
Subject: Readonly and Audience

Hey Guys,

I was thinking about this, and I really don’t like the proposed solution for getting the current user for the audience. I think it requires some pretty nasty code to handle all cases. What is the worry about delaying connected until the user is in it’s own audience? 

-Tony

**Comment by vladsud** [comment] 2021-05-28 17:14
Related: #5251, #1839

**Comment by markfields** [comment] 2022-03-18 23:51
I'm closing this one as a dupe of "fresher" issue #7275.  But this is super helpful context/back-story to refer to.

**Closed** 2022-03-18 23:52 UTC
Labels: api, design-required
