### ISSUE TITLE
Re-enable 'test:realsvc' on Tinylicious after addressing stability issues

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#6006] opened 2021-04-30 21:14 UTC
## Describe the bug
Not specific to code coverage.  Running `test:realsvc` often fails 1 or 2 tests from AgentScheduler and/or DetachedContainer.

This was blocking `ci:test:coverage` and consequently publishing and downstream ODSP tests, so I've modified 'test:report' in the root package.json to exclude 'test:realsvc' for now. 

### To Reproduce
1. `npm run test:realsvc`

### Logs
Example log from a bad run:
```
@fluidframework/test-end-to-end-tests:   1) AgentScheduler
@fluidframework/test-end-to-end-tests:        compat N-2 - new driver
@fluidframework/test-end-to-end-tests:          Single client
@fluidframework/test-end-to-end-tests:            "before each" hook for "Can pick tasks":
@fluidframework/test-end-to-end-tests:      Uncaught Error: read ECONNRESET
@fluidframework/test-end-to-end-tests:       at createR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:19:20)
@fluidframework/test-end-to-end-tests:       at Object.throwR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:35:26)
@fluidframework/test-end-to-end-tests:       at RouterliciousStorageRestWrapper.request (/workspaces/f2/packages/drivers/routerlicious-driver/dist/restWrapper.js:61:26)
@fluidframework/test-end-to-end-tests:       at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:   2) AgentScheduler
@fluidframework/test-end-to-end-tests:        compat N-2 - new driver
@fluidframework/test-end-to-end-tests:          Multiple clients
@fluidframework/test-end-to-end-tests:            "before each" hook for "No tasks initially":
@fluidframework/test-end-to-end-tests:      Error: read ECONNRESET
@fluidframework/test-end-to-end-tests:       at createR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:19:20)
@fluidframework/test-end-to-end-tests:       at Object.throwR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:35:26)
@fluidframework/test-end-to-end-tests:       at RouterliciousOrdererRestWrapper.request (/workspaces/f2/packages/drivers/routerlicious-driver/dist/restWrapper.js:61:26)
@fluidframework/test-end-to-end-tests:       at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:   3) AgentScheduler
@fluidframework/test-end-to-end-tests:        compat N-2 - old container runtime
@fluidframework/test-end-to-end-tests:          Single client
@fluidframework/test-end-to-end-tests:            "before each" hook for "No tasks initially":
@fluidframework/test-end-to-end-tests:      Error: socket hang up
@fluidframework/test-end-to-end-tests:       at createR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:19:20)
@fluidframework/test-end-to-end-tests:       at Object.throwR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:35:26)
@fluidframework/test-end-to-end-tests:       at RouterliciousOrdererRestWrapper.request (/workspaces/f2/packages/drivers/routerlicious-driver/dist/restWrapper.js:61:26)
@fluidframework/test-end-to-end-tests:       at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:   4) AgentScheduler
@fluidframework/test-end-to-end-tests:        compat N-2 - new driver
@fluidframework/test-end-to-end-tests:          Single client
@fluidframework/test-end-to-end-tests:            "before each" hook for "Can pick tasks":
@fluidframework/test-end-to-end-tests:      done() called multiple times in hook <AgentScheduler compat N-2 - new driver Single client "before each" hook for "Can pick tasks"> of file /workspaces/f2/packages/test/test-end-to-end-tests/dist/test/agentScheduler.spec.js; in addition, done() received error: Error: Runtime is closed
@fluidframework/test-end-to-end-tests:     at RuntimeWithRequestHandler.verifyNotClosed (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:671:19)
@fluidframework/test-end-to-end-tests:     at RuntimeWithRequestHandler.submit (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:598:14)
@fluidframework/test-end-to-end-tests:     at RuntimeWithRequestHandler.submitChannelOp (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:595:14)
@fluidframework/test-end-to-end-tests:     at /workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:231:203
@fluidframework/test-end-to-end-tests:     at ChannelDeltaConnection.submitFn (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/channelContext.js:13:126)
@fluidframework/test-end-to-end-tests:     at ChannelDeltaConnection.submit (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/channelDeltaConnection.js:52:14)
@fluidframework/test-end-to-end-tests:     at SharedDirectory.submitLocalMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/shared-object-base/dist/sharedObject.js:229:43)
@fluidframework/test-end-to-end-tests:     at SharedDirectory.submitDirectoryMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:355:14)
@fluidframework/test-end-to-end-tests:     at SubDirectory.submitKeyMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:1002:24)
@fluidframework/test-end-to-end-tests:     at SubDirectory.set (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:718:14)
@fluidframework/test-end-to-end-tests:     at SharedDirectory.set (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:227:19)
@fluidframework/test-end-to-end-tests:     at Context.<anonymous> (/workspaces/f2/packages/test/test-end-to-end-tests/dist/test/agentScheduler.spec.js:28:30)
@fluidframework/test-end-to-end-tests:     at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:   Error: done() called multiple times in hook <AgentScheduler compat N-2 - new driver Single client "before each" hook for "Can pick tasks"> of file /workspaces/f2/packages/test/test-end-to-end-tests/dist/test/agentScheduler.spec.js; in addition, done() received error: Error: Runtime is closed
@fluidframework/test-end-to-end-tests:       at RuntimeWithRequestHandler.verifyNotClosed (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:671:19)
@fluidframework/test-end-to-end-tests:       at RuntimeWithRequestHandler.submit (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:598:14)
@fluidframework/test-end-to-end-tests:       at RuntimeWithRequestHandler.submitChannelOp (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:595:14)
@fluidframework/test-end-to-end-tests:       at /workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/dataStoreRuntime.js:231:203
@fluidframework/test-end-to-end-tests:       at ChannelDeltaConnection.submitFn (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/channelContext.js:13:126)
@fluidframework/test-end-to-end-tests:       at ChannelDeltaConnection.submit (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/datastore/dist/channelDeltaConnection.js:52:14)
@fluidframework/test-end-to-end-tests:       at SharedDirectory.submitLocalMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/shared-object-base/dist/sharedObject.js:229:43)
@fluidframework/test-end-to-end-tests:       at SharedDirectory.submitDirectoryMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:355:14)
@fluidframework/test-end-to-end-tests:       at SubDirectory.submitKeyMessage (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:1002:24)
@fluidframework/test-end-to-end-tests:       at SubDirectory.set (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:718:14)
@fluidframework/test-end-to-end-tests:       at SharedDirectory.set (/workspaces/f2/packages/test/test-version-utils/node_modules/.legacy/0.38.4/node_modules/@fluidframework/map/dist/directory.js:227:19)
@fluidframework/test-end-to-end-tests:       at Context.<anonymous> (dist/test/agentScheduler.spec.js:28:30)
@fluidframework/test-end-to-end-tests:       at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:       at runMicrotasks (<anonymous>)
@fluidframework/test-end-to-end-tests:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
@fluidframework/test-end-to-end-tests:   5) Detached Container
@fluidframework/test-end-to-end-tests:        compat N-2 - old data runtime
@fluidframework/test-end-to-end-tests:          Load attached container and check for dataStores:
@fluidframework/test-end-to-end-tests:      Error: socket hang up
@fluidframework/test-end-to-end-tests:       at createR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:19:20)
@fluidframework/test-end-to-end-tests:       at Object.throwR11sNetworkError (/workspaces/f2/packages/drivers/routerlicious-driver/dist/errorUtils.js:35:26)
@fluidframework/test-end-to-end-tests:       at RouterliciousOrdererRestWrapper.request (/workspaces/f2/packages/drivers/routerlicious-driver/dist/restWrapper.js:61:26)
```

**Comment by curtisman** [comment] 2021-05-13 13:53
I believe this is caused by port exhaustion because of TIME_WAIT delay on TCP sockets disconnection.

**Comment by anthony-murphy** [comment] 2021-12-10 20:53
did we ever figure out the problem here. will #7909  help?

**Comment by curtisman** [comment] 2022-06-16 02:33
@justus-camp this is done, right? should we close this?

**Closed by curtisman** 2022-06-16 02:33 UTC
Labels: bug, area: tests, src: test failure

**Comment by justus-camp** [comment] 2022-06-16 20:43
Yeah this is done. I messed up the "fixes" syntax in the PR that should've closed this one
