### ISSUE TITLE
FluidHelloWorld demo error

### ISSUE THREAD

**Issue by zhaoyiming0803** [microsoft/FluidFramework#8573] opened 2021-12-16 09:58 UTC
### To Reproduce
1. git clone https://github.com/microsoft/FluidHelloWorld.git
2. cd FluidHelloWorld
3. npm install
4. npm run start
5. the browser console reports an error, the page is blank, It will not work until it is refreshed several times

### Expected behavior
After the service is started successfully, the page is displayed normally

### Logs
common.js:113 fluid:telemetry:Container ContainerWarning {"category":"error","error":"Network Error","errorType":"throttlingError","errorInstanceId":"10a46d09-73c5-4790-921f-c7361b83d1bd","fluidErrorCode":"deltaManagerEmitDelayInfo","retryAfterSeconds":2,"innerErrorInstanceId":"2f6de816-75f4-496b-9201-2869ad257690","message":"Network Error","clientType":"interactive","loaderVersion":"0.48.3","containerId":"86f8ac32-8f0f-4343-9b48-c8f7721964ab","docId":"","containerAttachState":"Attaching","containerLoaded":true,"dmInitialSeqNumber":0,"dmLastKnownSeqNumber":0,"dmLastProcessedSeqNumber":0,"dmLastQueuedSeqNumber":0,"dmLastObservedSeqNumber":0,"connectionState":"Disconnected","connectionStateDuration":null,"loaderId":"c25d2643-d357-4b3f-b640-5d110a0ae621"} tick=220 Error    at createR11sNetworkError (http://localhost:8080/app.1d4a5a52d9965821e616.js:34242:20)    at throwR11sNetworkError (http://localhost:8080/app.1d4a5a52d9965821e616.js:34257:26)    at RouterliciousOrdererRestWrapper.request (http://localhost:8080/app.1d4a5a52d9965821e616.js:34463:86)    at async RouterliciousDocumentServiceFactory.createContainer (http://localhost:8080/app.1d4a5a52d9965821e616.js:33888:28)    at async runWithRetry (http://localhost:8080/app.1d4a5a52d9965821e616.js:20693:22)    at async Container.attach (http://localhost:8080/app.1d4a5a52d9965821e616.js:4409:32)    at async Object.attach (http://localhost:8080/app.1d4a5a52d9965821e616.js:49004:17)    at async createNewDice (http://localhost:8080/app.1d4a5a52d9965821e616.js:79548:16)    at async start (http://localhost:8080/app.1d4a5a52d9965821e616.js:79562:20) +0ms

**Comment by tylerbutler** [comment] 2021-12-16 19:53
I think this is a duplicate of #8413. A workaround is to run `npm run start:server` in a separate window, then run `npm run start:client`. #8413 will track a proper fix.

**Comment by zhaoyiming0803** [comment] 2021-12-17 02:11
Yes, question has solved. otherwise, do you know that how to use personal server code in Fluid Framework? do not to use primary server of Tinylicious service and Azure Fluid Relay.

**Comment by zhaoyiming0803** [comment] 2021-12-17 02:11
> I think this is a duplicate of #8413. A workaround is to run `npm run start:server` in a separate window, then run `npm run start:client`. #8413 will track a proper fix.

Yes, question has solved. otherwise, do you know that how to use personal server code in Fluid Framework? do not to use primary server of Tinylicious service and Azure Fluid Relay.

**Closed** 2021-12-20 12:00 UTC
Labels: bug, resolution: duplicate
